flags:
  text:
    integer-simple: false
packages:
- '.'
extra-deps:
- GLURaw-1.5.0.1
- GLUT-2.7.0.2
- HUnit-1.3.0.0
- MissingH-1.3.0.1
- ObjectName-1.1.0.0
- OpenGL-2.12.0.1
- OpenGLRaw-2.5.2.1
- StateVar-1.1.0.1
- adjunctions-4.2.1
- base-orphans-0.4.4
- bifunctors-5
- bytes-0.15.0.1
- cereal-0.4.1.1
- comonad-4.2.7.2
- contravariant-1.3.2
- distributive-0.4.4
- exceptions-0.8.0.2
- free-4.12.1
- hashable-1.2.3.3
- hslogger-1.2.9
- hxt-9.3.1.15
- hxt-charproperties-9.2.0.1
- hxt-regex-xmlschema-9.2.0.2
- hxt-unicode-9.0.2.4
- kan-extensions-4.2.2
- lens-4.12.3
- linear-1.19.1.3
- mtl-2.2.1
- nats-1
- network-2.6.2.1
- network-uri-2.6.0.3
- old-locale-1.0.0.7
- old-time-1.1.0.3
- parallel-3.2.0.6
- parsec-3.1.9
- prelude-extras-0.4
- primitive-0.6
- profunctors-5.1.1
- random-1.1
- reflection-2
- regex-base-0.93.2
- regex-compat-0.95.1
- regex-posix-0.95.2
- safe-0.3.9
- semigroupoids-5.0.0.4
- semigroups-0.16.2.2
- stm-2.4.4
- tagged-0.8.1
- text-1.2.1.3
- transformers-compat-0.4.0.4
- unordered-containers-0.2.5.1
- vector-0.11.0.0
- void-0.7
- zlib-0.6.1.1
- hspec-2.2.0
- QuickCheck-2.8.1
- hspec-core-2.2.0
- hspec-discover-2.2.0
- hspec-expectations-0.7.2
- ansi-terminal-0.6.2.3
- async-2.0.2
- quickcheck-io-0.1.2
- setenv-0.1.1.3
- tf-random-0.5
resolver: ghc-7.10
